version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

# docker-compose up --build
# (start both the database container and your Spring Boot application container)