replicaCount: 1
image:
  repository: some-docker-repo/bmc-test-java-service
  tag: latest
service:
  port: 8080
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
  memory: 64Mi